# Generated by Django 3.2.5 on 2021-07-29 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football_api_app', '0002_rename_nationality_football_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='football',
            name='average_goal_per_year',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='football',
            name='maximum_goal_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='football',
            name='minimum_goal_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='football',
            name='player_price',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='football',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='football',
            name='position',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
